### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by Bladrak** [thumbor-community/core#1]
Add some documentation based on thumbor's process to explain:
- how to install
- how to create a custom extension

**Comment by masom** [comment]
Sphinx auto-generated using https://readthedocs.org/ ?

**Comment by Bladrak** [comment]
Seems that's the way indeed. Otherwise you may rather like putting it to the Wiki?

**Comment by masom** [comment]
Readthedocs is great for that kind of stuff + allows documenting the API.

**Comment by masom** [comment]
More importantly is to have some kind of documentation that is up-to-date.
