### ISSUE TITLE
Incompatibility with tornado 4.5.0

### ISSUE THREAD

**Issue by ojrzenski** [thumbor-community/core#16]
Recent release of tornado 4.5.0 removed function **tornado.web._unquote_or_none** which is used in tc_core/web.py#L37.
Perhaps it should be fixed in thumbor setup, because it requires  "tornado>=4.1.0,<5.0.0", but it's still tc_core issue.

**Comment by Bladrak** [comment]
Thanks for reporting it. Indeed, we would need to update that on our side as well :)

**Comment by masom** [comment]
@ojrzenski I'll fix this ASAP.

**Comment by masom** [comment]
@ojrzenski We've just merged a PR that fixes the issue. I've tested with the latest tornado and 4.4, could you report back if everything works on your end?

**Comment by intellisense** [comment]
We are experiencing the same issue, the fix will do it but its not on pypi any plan for release?

**Comment by masom** [comment]
@intellisense Would you be able to use the repo master branch and confirm this fixes the issues?

```
pip install -e git+https://github.com/thumbor-community/core.git#egg=tc_core
```

I'll try to push something to pypi soon after I can confirm everything is fixed.

**Comment by intellisense** [comment]
@masom I can confirm this fixes the issue. Thanks!

**Comment by masom** [comment]
👍 I've tagged the current master as 0.4.1 but I plan on unlocking the thumbor version to just be ">= 5"

PyPi will get 0.4.2

**Comment by intellisense** [comment]
Cool! I have also created a thumbor extension [tc_pdf](https://github.com/intellisense/tc_pdf) (Preview for PDF) your feedback and suggestions on improvements will be highly appreciated. Thanks!
