### ISSUE TITLE
for the core-0.4.1 can't be installed on https://pypi.org/

### ISSUE THREAD

**Issue by Tideorz** [thumbor-community/core#18]
the tc-core-0.4.1 fix the bug about tornado's util method _unquote_or_none move from web.py to routing.py, But this version can't be found on pypi. Hope it can be release to pypi. Thanks :)

**Comment by dgarana** [comment]
@Tideorz although it's not the best approach, you can add the requirement with "pip install git+https://github.com/thumbor-community/core" for now.

**Comment by masom** [comment]
Sorry about this, I'll push the latest version today.

**Comment by masom** [comment]
https://pypi.org/project/tc_core/#history

0.4.1 has been pushed. Sorry for forgetting this for like 2 years.
