### ISSUE TITLE
Support for Thumbor 7 / Python 3

### ISSUE THREAD

**Issue by Bladrak** [thumbor-community/core#21]
Following the discussions on https://github.com/thumbor-community/core/issues/20

We should support Thumbor 7 and Python 3 with this extension. If anyone's up to it don't hesitate to let me know, I'll be happy to review :-)

**Comment by Krinkle** [comment]
@gi11es wrote at https://github.com/thumbor-community/core/issues/20#issuecomment-667853528

> We use it in production for Wikipedia, as a way to bring in our custom handlers […]
> > Should we plan for a python 3 / thumbor 7 upgrade then?
> Yes. If nobody gets around to it, we will have to handle it. Currently we're waiting for Thumbor 7 to be stable before we start working on our migration effort.

The latest version of the thumbor.conf customisation is now documented at [wikimedia_thumbor/README.md](https://github.com/wikimedia/operations-software-thumbor-plugins/blob/e1911ded49702da548cfc1f624d3444ec000ec19/README.md#quick-setup-for-local-development).

As part of our Python 3 transition, Wikimedia has (for now) forked this code within our plugin and carried out the Python 3 and Thumbor 7 upgrades in-place:

* https://github.com/wikimedia/operations-software-thumbor-plugins/tree/40ffc66926/wikimedia_thumbor/core
* https://phabricator.wikimedia.org/T305053
* https://phabricator.wikimedia.org/T252719#8145948

**Comment by Bladrak** [comment]
Would you be up to submitting your fork as a PR to this repo? I'll be happy to review it.

**Comment by Krinkle** [comment]
@Bladrak It is my understanding that it was intentionally not upstreamed, much to my disappointment. I've asked the team in question to reconsider.

**Comment by Bladrak** [comment]
All right let me know, thanks!

**Comment by Bladrak** [comment]
Supported since 0.5
