### ISSUE TITLE
Set up pip installation on all packages

### ISSUE THREAD

**Issue by Bladrak** [thumbor-community/core#6]
- Prefix modules with `tc_`
- Write `setup.py` files
- Register packages on pip

**Comment by masom** [comment]
AWS needs to be renamed tc_aws

**Comment by Bladrak** [comment]
See https://github.com/thumbor-community/aws/pull/7

**Comment by Bladrak** [comment]
@masom seems everything is done here, isn't it?

**Comment by masom** [comment]
Yep!
